services:
  client:
    build: ./client
    container_name: chess_client
    ports:
      - "${VITE_PORT}:${VITE_PORT}"
    depends_on:
      - server
    env_file:
      - .env
    volumes:
      - ./client:/app
      - /app/node_modules
    restart: unless-stopped
    environment:
      - CHOKIDAR_USEPOLLING=true
  server:
    build: ./server
    container_name: chess_server
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
      - "4000:4000"
      - "5555:5555"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./server:/app
      - /app/node_modules
    restart: unless-stopped
    environment:
      - SERVER_DATABASE_URL=${SERVER_DATABASE_URL}
  db:
    image: postgres:17.5-alpine
    container_name: chess_db
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
volumes:
  pgdata: